"""Render the Istio VirtualService for a cutover phase.

The controller never touches the cluster directly. Each decision is rendered
to a manifest and committed to the GitOps repo; Argo CD syncs it. That gives
an auditable, revertible history of every traffic change ("git revert" is the
manual rollback), and keeps the touchless-deployment model from the JD.
"""

from __future__ import annotations

from .traffic import Phase

_TEMPLATE = """\
# Generated by cutover.gitops for phase "{phase}" - do not edit by hand.
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: orders-cutover
  namespace: orders
  labels:
    app.kubernetes.io/managed-by: cutover-controller
    cutover.example.com/phase: "{phase}"
spec:
  hosts:
    - orders.example.com
  gateways:
    - istio-ingress/public-gateway
  http:
    - name: primary
      route:
        - destination:
            host: orders-legacy.orders.svc.cluster.local  # ServiceEntry -> AWS internal ALB over HA VPN
          weight: {source_weight}
        - destination:
            host: orders.orders.svc.cluster.local
            subset: gcp
          weight: {target_weight}
{mirror}      retries:
        attempts: 2
        perTryTimeout: 2s
        retryOn: gateway-error,connect-failure,refused-stream
"""

_MIRROR = """\
      mirror:
        host: orders.orders.svc.cluster.local
        subset: gcp
      mirrorPercentage:
        value: 100.0
"""


def render_virtualservice(phase: Phase, *, rolled_back: bool = False) -> str:
    target = 0 if rolled_back else phase.target_weight
    name = "rollback" if rolled_back else phase.name
    mirror = _MIRROR if (phase.mirror and not rolled_back) else ""
    return _TEMPLATE.format(
        phase=name, source_weight=100 - target, target_weight=target, mirror=mirror
    )
